#!/usr/bin/env python3
"""
gen_graphifyignore.py — generate a privacy-safe .graphifyignore for the vault.

Graphify indexes the whole folder unless ignored. Privacy here is folder-only (see
privacy_guard.py), so this file is a static list — nothing is scanned or opened to build it.

Excludes:
  - the private folder        — journal + every private file (privacy rule)
  - anything starting with `_` — generated system files
  - `graphify-out/`, `vector-out/` — derived outputs
  - `6 - Images/`, `.obsidian/`, `.git/`, templates, logs — noise

Usage:
  python3 "0 - System/scripts/gen_graphifyignore.py"          # dry-run (print)
  python3 "0 - System/scripts/gen_graphifyignore.py" --apply  # write .graphifyignore
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from privacy_guard import PRIVATE_DIR  # noqa: E402

SCRIPT_DIR = Path(__file__).resolve().parent
VAULT = SCRIPT_DIR.parent.parent


STATIC_ENTRIES = [
    f"{PRIVATE_DIR}/",
    "graphify-out/",
    "vector-out/",
    "6 - Images/",
    ".obsidian/",
    ".git/",
    ".backup/",
    "**/.backup/",
    "_*",
    "**/_*",
    # noise, not knowledge: the operations log, templates, infrastructure files
    "7 - Wikipedia/log.md",
    "4 - Templates/",
    "home.html",
    ".mcp.json",
    ".claude/",
]

def main():
    apply = "--apply" in sys.argv[1:]

    lines = ["# .graphifyignore — auto-generated by gen_graphifyignore.py",
             "# Privacy-safe: the private folder and _underscore files are excluded.",
             ""]
    lines += STATIC_ENTRIES
    content = "\n".join(lines) + "\n"

    dest = VAULT / ".graphifyignore"
    if apply:
        dest.write_text(content, encoding="utf-8")
        print(f"Wrote {dest}")
        print(f"  {len(STATIC_ENTRIES)} static patterns.")
    else:
        print("DRY-RUN (use --apply to write .graphifyignore)\n")
        print(content)


if __name__ == "__main__":
    main()
