#!/usr/bin/env python3
"""
gen_graphifyignore.py — generate a privacy-safe .graphifyignore for the vault.

Graphify indexes the whole folder unless ignored. Its .graphifyignore is PATH-based
(gitignore-style), but our privacy model is partly CONTENT-based (`private: true` in
frontmatter can appear in any file). This script bridges the gap: it emits an ignore
entry for every private surface so Graphify never indexes it.

Excludes:
  - `3 - Journal/`          — the personal journal (never even opened here)
  - any file with `private: true` in its YAML frontmatter
  - anything starting with `_`
  - `graphify-out/`         — Graphify's own output
  - `6 - Images/`, `.obsidian/`, `.git/` — noise

Usage:
  python3 "0 - System/scripts/gen_graphifyignore.py"          # dry-run (print)
  python3 "0 - System/scripts/gen_graphifyignore.py" --apply  # write .graphifyignore
"""

import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
VAULT = SCRIPT_DIR.parent.parent

JOURNAL_DIR = "3 - Journal"
# directories we never descend into (journal is never read, per privacy rules)
PRUNE_DIRS = {JOURNAL_DIR, ".git", ".obsidian", "graphify-out", "6 - Images"}

STATIC_ENTRIES = [
    f"{JOURNAL_DIR}/",
    "graphify-out/",
    "6 - Images/",
    ".obsidian/",
    ".git/",
    ".backup/",
    "**/.backup/",
    "_*",
    "**/_*",
    # noise — not knowledge: operational log, templates, infra files
    "7 - Wikipedia/log.md",
    "4 - Templates/",
    ".mcp.json",
    ".claude/",
]

FM_PRIVATE = re.compile(r"^\s*private:\s*true\s*$", re.MULTILINE)


def has_private_frontmatter(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return False
    if not text.startswith("---"):
        return False
    end = text.find("\n---", 3)
    if end == -1:
        return False
    return bool(FM_PRIVATE.search(text[:end]))


def find_private_files():
    private = []
    for path in sorted(VAULT.rglob("*.md")):
        rel_parts = path.relative_to(VAULT).parts
        # never descend into pruned dirs (journal is never opened)
        if any(part in PRUNE_DIRS for part in rel_parts[:-1]):
            continue
        if path.name.startswith("_"):
            continue  # already covered by _* pattern
        if has_private_frontmatter(path):
            private.append(path.relative_to(VAULT).as_posix())
    return private


def main():
    apply = "--apply" in sys.argv[1:]
    private = find_private_files()

    lines = ["# .graphifyignore — auto-generated by gen_graphifyignore.py",
             "# Privacy-safe: journal, private-flagged, and _underscore files are excluded.",
             ""]
    lines += STATIC_ENTRIES
    lines += ["", f"# files with `private: true` frontmatter ({len(private)} found):"]
    lines += ["/" + p for p in private]
    content = "\n".join(lines) + "\n"

    dest = VAULT / ".graphifyignore"
    if apply:
        dest.write_text(content, encoding="utf-8")
        print(f"Wrote {dest}")
        print(f"  {len(STATIC_ENTRIES)} static patterns + {len(private)} private files excluded.")
    else:
        print("DRY-RUN (use --apply to write .graphifyignore)\n")
        print(content)
        print(f"[{len(private)} private files would be excluded]")


if __name__ == "__main__":
    main()
