#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
okf_verify.py — mark that you have read a page and confirmed it is correct.

This is the distinction the vault had no way to express until now:
  generated  = who produced this (an agent / the compile pipeline / you)
  verified   = who *reviewed* it and signed off

Without `verified` a page is "unverified" under OKF — even if it is perfectly accurate.

Usage:
    python3 "0 - System/scripts/okf_verify.py" "7 - Wikipedia/Stop Loss.md"
    python3 "0 - System/scripts/okf_verify.py" "7 - Wikipedia/"*.md
    python3 "0 - System/scripts/okf_verify.py" --list        # what is already verified
    python3 "0 - System/scripts/okf_verify.py" --pending     # what is waiting for sign-off

Set OKF_ACTOR to your own identity (default: human:me).
"""
import os, sys, argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import vaultlib as V

ACTOR = os.environ.get("OKF_ACTOR", "human:me")


def all_pages():
    for it in (V.iter_wiki_pages(), V.iter_notes(), V.iter_topics()):
        yield from it


def is_verified(meta):
    ver = meta.get("verified")
    return bool(ver) and isinstance(ver, list)


def stamp(paths):
    touched = []
    for raw in paths:
        p = Path(raw)
        if not p.is_absolute():
            p = V.VAULT / raw
        if not p.exists():
            print(f"  ⚠️  not found: {raw}")
            continue
        if V.is_forbidden(p):
            print(f"  ⛔ out of bounds: {raw}")
            continue
        meta, body = V.read_page(p)
        if not meta:
            print(f"  ⚠️  no frontmatter: {V.rel(p)}")
            continue
        if str(meta.get("private", "")).lower() == "true":
            print(f"  ⛔ private file: {V.rel(p)}")
            continue
        entry = {"by": ACTOR, "at": V.today()}
        ver = meta.get("verified") or []
        if not isinstance(ver, list):
            ver = []
        if any(isinstance(e, dict) and e.get("by") == ACTOR for e in ver):
            print(f"  ↻  already verified: {V.rel(p)}")
            continue
        meta["verified"] = ver + [entry]
        touched.append((p, meta, body))

    if not touched:
        return
    V.backup([p for p, _, _ in touched], "verify")
    for p, meta, body in touched:
        p.write_text(V.render_page(meta, body), encoding="utf-8")
        print(f"  ✅ {V.rel(p)}")
    print(f"\n{len(touched)} pages marked verified by {ACTOR}.")


def main():
    ap = argparse.ArgumentParser(add_help=True)
    ap.add_argument("paths", nargs="*", help="files to stamp")
    ap.add_argument("--list", action="store_true", help="what is already verified")
    ap.add_argument("--pending", action="store_true", help="what is waiting for sign-off")
    args = ap.parse_args()

    if args.list or args.pending:
        want = args.list
        rows = [(V.rel(p), meta) for p, meta, _ in all_pages()
                if is_verified(meta) == want]
        title = "Verified" if want else "Awaiting sign-off"
        print(f"{title}: {len(rows)}\n")
        for rel, meta in rows:
            if want:
                who = ", ".join(f"{e.get('by')}@{e.get('at')}"
                                for e in meta["verified"] if isinstance(e, dict))
                print(f"  ✅ {rel}  ({who})")
            else:
                by = str(meta.get("generated_by", "") or "").strip() or "?"
                print(f"  ⬜ {rel}  (generated by {by})")
        return

    if not args.paths:
        ap.print_help()
        return
    stamp(args.paths)


if __name__ == "__main__":
    main()
